const ProjectData = [
  {
    id: 0,
    title: "ShoeShop / 신발 쇼핑몰",
    stack: "React, Redux",
    content: "장바구니 기능과 Ajax 요청으로 데이터 불러오기를 구현한 사이트입니다.",
    date: "1인 개발 / 22년 1월 제작",
    img: "https://ifh.cc/g/Fia5g9.jpg",
    link: "https://github.com/AinRuthPai/react-shoppingmall",
  },
  {
    id: 1,
    title: "포트폴리오 웹사이트",
    stack: "React",
    content: "지금 보고 계신 사이트입니다.",
    date: "1인 개발 / 22년 2월 제작",
    img: "https://ifh.cc/g/tSckA6.jpg",
    link: "https://github.com/AinRuthPai/portfolio-website-react",
  },
  {
    id: 2,
    title: "KaKaoTalk",
    stack: "HTML, CSS",
    content: "카카오톡 클론 코딩입니다.",
    date: "1인 개발 / 21년 8월 제작",
    img: "https://ifh.cc/g/9GvRDw.png",
    link: "https://github.com/AinRuthPai/kokoa-clone-2021",
  },
  {
    id: 3,
    title: "그림판",
    stack: "HTML, CSS, JavaScript",
    content: "배경 채우기 & 그리기, 선 굵기, 지우개, 색 선택 기능이 구현된 그림판입니다.",
    date: "1인 개발 / 22년 3월 제작",
    img: "https://ifh.cc/g/cNoXGY.png",
    link: "https://github.com/AinRuthPai/paintBoardJs",
  },
  {
    id: 4,
    title: "테트리스",
    stack: "HTML, CSS, JavaScript",
    content: "주로 활용되는 canvas 대신에 DOM을 활용한 테트리스 게임입니다.",
    date: "1인 개발 / 22년 3월 제작",
    img: "https://ifh.cc/g/QmjggH.png",
    link: "https://github.com/AinRuthPai/tetris",
  },
  {
    id: 5,
    title: "영화 순위 사이트",
    stack: "NextJS",
    content: "영화 API 데이터를 fetch하여 제작한 웹사이트입니다.",
    date: "1인 개발 / 22년 3월 제작",
    img: "https://ifh.cc/g/DmAwdR.jpg",
    link: "https://github.com/AinRuthPai/nextjs-lecture",
  },
];

export default ProjectData;
